server:
  port: 8081


spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
    username: root
    password: root